- README.md
- files/mote.spec
- mote/__init__.py
- mote/soke.py
- requirements.txt
Since `python-pylibmc` is not available in EPEL7, we are migrating to `python-memcached`.
> Migrate to python-memcache

- mote/__init__.py
- mote/static/js/single-log.js
- mote/static/js/sresults.js
POST doesn't actually make sense here.  It is for when you want to
*change* some data on the server.  Here, we are just requesting that the
server send us some logs -- so that should be a *GET*.
Furthermore, POSTs make things unnecessarily hard to debug, since you can't
easily copy around URLs from the developer console to play with.
I also modified those flask endpoints to return real ``404`` status codes.
If we want to markup 404 pages, we can add a flask 404 handler to catch and
decorate those.
> Convert POST endpoints to GET.

- mote/soke.py
And also complain loudly when we cannot parse a date.
This is should fix #25.
We were failing to parse some dates and returning 'Date Undefined' which was then being cached and causing problems in other parts of the stack which tried to parse that string.
> Loosen requirements on date parsing regex.

- README.md
- mote/templates/base.html
- mote/templates/debug-list.html
- mote/templates/index.html
threebean.org does not support https, therefore always use http. The
other links support https, so use them always. Also remove an unneeded
URL parameter from the wiki link.
> Use https/http where appropriate

- README.md
- category_mappings.json
- mote/templates/browse.html
- name_mappings.json
This pull request adds several new name mappings for different sub-projects or groups in Fedora, such as the Fedora Council, Fedora CommOps, Fedora EMEA Ambassadors, and the Fedora Magazine.
Additionally, it also alphabetizes all existing lists to help improve navigation and user-friendliness for those browsing to find meetings.
Also, minor adjustment to README to change `yum` to `dnf`.
> Add new name mappings, add new category and categorize new names

- mote/soke.py
This issue was noted by `robyduck` on IRC. 
Specifically, this team was not showing up in search due to its symbols in its filename. 
See https://meetbot.fedoraproject.org/sresults/?group_id=fedora-it_-_incontro_periodico_della_comunita_italiana&type=team
However, it seems like it is now showing up through search. @puiterwijk, did you launch a hotfix to fix this or did it fix itself?
This patch loosens certain aspects of the regex and adds better heuristics for the filename ending, to prevent filenames with `-` symbols from interfering with the date and file extension detection mechanisms.
> Fix regex to catch correct segment of filename

- mote/__init__.py
- Whenever the channel name is provided when requesting single logs, attempt to fetch based on the meeting channel rather than the team name.
- Remove redundancy associated with meeting date requests
> Fix #83, fetch from channel whenever possible for single logs

- name_mappings.json
Adds a new alias for the `fedora-mktg` team. Ran the tests script and all checked out.
> Add new fedora-mktg alias

- mote/__init__.py
Uses the traceback module to output Flask's caught errors onto `stderr`.
> Output traceback from 500 handled errors onto stderr

- category_mappings.json
- name_mappings.json
This commit does a couple of things:
* Adds the APAC Ambassadors to the Meetbot teams page for improved accessibility
* Changes the friendly names of all Ambassadors to be a little more consistent (i.e. `"[region] Ambassadors ([full region name])`")
* Swaps the Marketing meetings to use `marketing` as the primary meeting name, `fedora-mktg` as the alias
* The Marketing team hasn't met under the name `fedora-mktg` for a few years
----
cc: @sachinkamath
> Add / standardize Ambassadors, swap Marketing names

- README.md
This commit tries to improve the instruction on how to install mote, making it clear that packages on `requirements.txt` must be installed beforehand.
> improve instruction on how to install the package, fixes #119

- mote/static/js/sresults.js
| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/27789806/75189952-ec154200-5714-11ea-8a4c-d57afa9071a9.png) | ![image](https://user-images.githubusercontent.com/27789806/75190010-0cdd9780-5715-11ea-8bbf-f2f6fde254bb.png) |
> Fix syntax highliting in meeting logs

- category_mappings.json
- name_mappings.json
This commit makes several changes to the definitions of different teams
in Fedora. Originally I only wanted to add the Arch Linux Women
community, but ended up fixing some broken names and adding newer teams
like Diversity & Inclusion and Mindshare Committee to the teams list.
I also tried a more intuitive way of sorting all the teams by categories
that aligns more closely with the Fedora org chart created by @mattdm:
https://docs.fedoraproject.org/en-US/project/orgchart/
cc: @FunnelFiasco @cverna @cydrobolt @riecatnor @x3mboy @nasirhm
> categories/names: Refactor for 2020

- .travis.yml
This commit reworks the Travis CI config to run in a more modern
environment. The original Travis file is carried over for many years. In
short, this commit does the following:
* Bumps build env from Ubuntu Xenial to Ubuntu Bionic
* Utilizes pip caching for faster build times
* Sends status notifications to `#fedora-mote` on Freenode IRC
> ci: Modernize Travis CI config

- .travis.yml
- Pipfile
- Pipfile.lock
This commit raises Møte's supported Python version to Python 3.9. In the
upcoming Fedora 33 release, Fedora 3.9 becomes the default version of
the Python interpreter. So, this follows Fedora's precedent by using the
latest version of upstream Python.
Since we are still early in development, we can be more flexible about
this for now.
Part of #126, but does not complete it.
> Pipfile: Upgrade env to Python 3.9

- Pipfile
- Pipfile.lock
Version Bumping from flask 0.10.1 to 1.1.2 to make sure to work on the latest framework and use it's functionalities.
Ticket: https://github.com/fedora-infra/mote/issues/138
cc: @HiraTariq-01
> Version bumped flask to 1.1.2

- mote/static/css/mote.css
This PR is for [issue#62](https://github.com/fedora-infra/mote/issues/62) to fix the word wrapping issue.
> wrap text properly in log display

- src/mote/modules/late.py
With reference to PR #200 `ctime` is no longer being used in `late.py` and hence is redundant and should be removed.
@darknao @t0xic0der
> remove unused ctime import

- src/mote/templates/e404page.html
Closes #211 
Added footer in 404-error page.
> Added footer in 404 page

- Dockerfile
- fedora-messaging.toml
- requirements.txt
- src/mote/main.py
- src/mote/templates/mainpage.html
I've took the work from @subhangi2731 and adapt it a little to work with fedora-messaging.
I've switched the docker image from alpine to fedora-minimal as it is way faster to build and don't need to compile most of the python packages.
Notifications have been tweaked a bit to keep them minimal and less intrusive. They stay on screen until dismissed, as it's very unlikely the user happen to be actively monitoring the page in the 5 seconds time frame a meeting just ended.
For now, the meeting link is the one provided in the fedora-messaging bus, and redirect to meetbot.fp-o.
> Implement Fedora messaging notifications

- mote/util.py
From time to time, the cache file get truncated. While I do not know
why, I see that it result in error 500 with the following traceback:
2022-02-24 11:19:28,488 Exception on / [GET]
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return …
> Detect cache corruption and work around them

- mote/main.py
- mote/tasks.py
For testing purposes, we are currently downloading new meeting files from meetbot-raw when notified by fedora-messaging.
Now that we are in production, we don't need to do that anymore as we already have direct access to all meeting files locally.
Additionally, the filesystem is read-only, so the update logic is failing and prevent the calendar view from showing any new meeting.
The second commit is fixing #321 by redirecting the user to meetbot-raw when requesting meeting logs in (raw) text format.
> A couple of fixes

- mote/static/css3/fragment.css
before / after:
light mode for reference:
Thoughts?
Fix #322
> improve darktheme for log view

- .github/workflows/main.yml
In its current configuration, CI jobs are run twice on PRs from feature branch (or dependabot ones): 
- first one for the `push` event on said branch
- and second one for the `pull_request` event toward the `main` branch
This PR should prevent that.
> avoid running duplicate jobs on PR

- mote/static/css3/fragment.css
- mote/templates/event_summary.html
Add dropdowns to [Full Logs] and [Permalink] buttons to select between html and text version.
> Add links for plain text logs/minutes (#342)

- mote/consume.py
- mote/modules/redis.py
- mote/tasks.py
- mote/worker.py
Allows setting a Redis password with either `REDIS_PASSWORD` env var, or `CACHE_REDIS_PASSWORD` configuration setting, that can be used by all components (cache, worker queue and socketio).
> add support for Redis password

- mote/templates/base.html.j2
Related to #338 
Some meetings name like `FPC` are too short and cannot be looked up with the current setting.
> lower search restriction to 3 characters

- mote/tasks.py
The `process_new_meet` function which is responsible to update the cache, is not injecting the correct filename.
This make new meetings not available through the search engine until the cache is rebuilt.
> fix cache update on new meet

- mote/modules/find.py
- mote/templates/base.html.j2
- tests/test_find.py
- tests/test_fragedpt.py
Uses ISO8601 date format when needed to make date conversion reliable and locale independent.
Also uses timestamp to sort meetings in search results.
Should fix #338.
> use iso8601 format for date in backend for reliability

- mote/main.py
- mote/modules/converters.py
- mote/templates/event_summary.html.j2
- mote/templates/statfile.html.j2
- tests/test_meeting_logs.py
Introduce `DateConverter` that takes (and validates) date in `YYYY-mm-dd` format and return a `datetime` object.
This makes sure routes can no longer accept unexpected URI such as `/aaa/bbb/ccc` or any other three-part URIs that we might use in the future.
> Add type check for all urls patterns

- mote/main.py
- mote/modules/late.py
So we can handle meeting with # sign in their name.
https://meetbot.fedoraproject.org/fedora-meeting/2022-08-17/fedora_iot_working_group_meeting_#chair_pwhalen_pbrobinson_bcotton_tdawson_puiterwijk_coremodule_#topic_roll_call.2022-08-17-15.01.html
(that doesn't work)
to 
https://meetbot.fedoraproject.org/fedora-meeting/2022-08-17/fedora_iot_working_group_meeting_%23chair_pwhalen_pbrobinson_bcotton_tdawson_puiterwijk_coremodule_%23topic_roll_call.2022-08-17-15.01.html
> encode uri where needed

- mote/worker.py
rq.Connection no longer exists and needs to be replaced with explicit connection management.
> redis rq.Connection context are deprecated
