fedora-infra/mote

mote/static/js/index-vars.js

Selecting a search item should automatically navigate to it.

---

README.md
mote/__init__.py
mote/static/js/search.js
mote/util.py
requirements.txt

Sort search results by most-recent-meetings first.

---

mote/fedmsg_consumer.py

Also enhance logging for mote-updater.

Run the teams cronjob right after meetings end.

---

mote/__init__.py

The ``from util import ...`` line, does an import of config in the util.py file.

Move insertion of MOTE_FOLDER_PATH to *before* the first import of config.

---

mote/__init__.py

This should fix #48 for @Grinnz.

Redirect old teams requests to the new location.

---

mote/static/js/sresults.js

Rename "View Log" to just "View".

---

mote/__init__.py
mote/templates/sresults.html

Show a button to directly show latest meeting

---

category_mappings.json
name_mappings.json

Added g11n category as well as name mappings

mappings: Add g11n category as well as name mappings

---

files/test_config.py
mote/__init__.py
mote/fedmsg_consumer.py
mote/soke.py
mote/static/js/search.js
mote/static/js/single-log.js
mote/static/js/sresults.js
mote/util.py
name_mappings.json
run_tests.sh
runmote.py
setup.py
tests/test_data_integrity.py
tests/test_soke.py
tests/test_util.py
tests/test_web.py

- Add aliasing
- Change year to 2016
- Remove redundancy in obtaining friendly name

Add aliasing

---

requirements.txt
run_tests.sh

Add pyflakes

---

category_mappings.json
name_mappings.json

Please let me know if there is the right way to add a new channel.

Add FZUG (#fedora-zh)

---

mote/static/js/single-log.js

Now when the page loads with a hash, it animates down to the appropriate location.

Hash on a link now scrolls to tm properly

---

files/config.py
files/test_config.py
mote/latest_meetings.py

Add datagrepper URL as option

---

mote/__init__.py
mote/static/css/mote.css
mote/static/js/single-log.js
mote/templates/single-log.html
mote/util.py

- Reformatted some code
- Added a deep link feature that allows users to select which type of log they would like to view, for links with the `.mtg` extension

Add feature for deep link, fix #94

---

category_mappings.json
name_mappings.json

This pull requests adds a mapping for the Fedora Badges team, which will begin meeting regularly on Wednesdays at 11:00 UTC.

Add Fedora Badges team mapping

---

mote/static/css/mote.css
mote/static/js/search.js

Add different icons in search results to differentiate types of groups

---

mote/__init__.py

Reverse date sorting on group pages

---

mote/__init__.py

Fix latest meeting button

---

README.md

Modified Documentation for Python 3
Usage of Pipenv to facilitate with the creation of Virtualenv and installation of packages inside it.
Fixes: #134 
Dependent on PR: #135

Documentation to run møte on Py3

---

src/mote/config.py
src/mote/main.py
src/mote/modules/call.py
src/mote/modules/find.py
src/mote/modules/late.py

A new `config.py` has been created to store the configuration that is commonly used across the project.
Closes #180

Create separate config file for frequently used configuration

---

src/mote/templates/e404page.html

The grey gradient theme was not applied on the 404-error page. This PR involves applying the same gradient to 404 page as well to maintain consistency across all pages.
Closes #208 
@darknao @t0xic0der Please review.

Change theme to grey across all pages

---

requirements.txt
setup.py
src/mote/main.py
src/mote/static/jscn/socket.io.js
src/mote/templates/mainpage.html

Using socket.io to send and receive data across browser and backend server. The function pings the endpoint every 5 seconds to fetch meetings that have been completed in the last 60 seconds and thus informing users for the recently finished meetings
Closes  #167

created websockets and toast popup for the recently finished meetings

---

.vscode/settings.json
src/mote/static/css3/fragment.css
src/mote/templates/mainpage.html

@t0xic0der @darknao  I spent a lot of time figuring out the way to display the list of meetings without interfering with the calendar and came up with the built-in bootstrap's dropdown solution. I have implemented fetching the meetings and displaying them as shown in the ss below, and will implement the show more button after this.

implementation of search bar to show the list of meetings in dropdown

---

.vscode/settings.json
README.md
requirements.txt

Changed the setup instructions in Readme file using poetry(dependency management and packaging in Python)

Change instructions in Readme.md file

---

poetry.lock

This reverts commit 0fe6a40a4ff7b46fe98c4d04c8852423eaf730ab.

Revert "Bump redis from 4.3.3 to 4.3.4"

---

mote/templates/aboutpage.html
mote/templates/e404page.html
mote/templates/mainpage.html
mote/templates/statfile.html

Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>
Fixes #363
@sanjayankur31, could you please take a look at this?
Before:
After:

Add project repo information in the footer

---

mote/templates/event_summary.html

Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>
Before:
Now:

Add uniform margins for modal header

---

README.md

Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>

Rework project documentation

---

.github/workflows/main.yml
doformat.sh
poetry.lock
pyproject.toml
tox.ini

Fixes https://github.com/fedora-infra/mote/issues/420

Reworked CI using Fedora Linux container

---

mote/main.py

Fix Meeting Logs being mislabel as "Minutes"

fix path extension parsing in statfile func

---

mote/templates/base.html.j2
mote/templates/statfile.html.j2

add OGP meta tags

---

mote/main.py
mote/modules/call.py
mote/modules/find.py
mote/static/css3/fragment.css
mote/static/jscn/calview.js
mote/templates/base.html.j2
mote/templates/event_summary.html.j2
tests/test_find.py
tests/test_fragedpt.py
tests/test_meeting_logs.py

This was sitting on staging for quite some time now.
I think it's time to push it on prod.
Close #364

add ability to browse adjacent meetings

---

poetry.lock
renovate.json

Tailor fit the renovate configuration

Tailor fit the renovate configuration

---

README.md

In response to @gridhead's comment https://github.com/fedora-infra/mote/issues/687#issuecomment-2055039522 requesting me to update README.md

Update README: replace Mega link with wget command

---

.github/workflows/main.yml
mote/modules/call.py
mote/modules/converters.py
poetry.lock
pyproject.toml
tox.ini

Move the code quality suite to Ruff

Move the code quality suite to Ruff
